language: java
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=2g -Xmx4g -Dfile.encoding=UTF-8"
    - JAVA_OPTS="-XX:MaxPermSize=2g -Xmx4g -Dfile.encoding=UTF-8"
script:
  - sudo mvn clean install -Pqulice --errors
sudo: required
services:
  - docker
